const styles = (theme) => ({
  root: {
    flexGrow: 1,
    // height: '100%',
  },
  darkModeRoot: {
    flexGrow: 1,
    backgroundColor: '#252525',
    height: '100%',
  },
  content: {
    padding: theme.spacing(2),
    color: theme.palette.text.secondary,
  },
  emptyRight: { width: '100%' },
  darkMode: {
    backgroundColor: '#252525',
    transition: '.5s',
    // height: '100vh',
  },
  darkModeMessage: {
    backgroundColor: '#262a30',
    transition: '.5s',
    height: '100vh',
  },
  lightMode: {
    backgroundColor: 'white',
    transition: '.5s',
  },
  introduction: {
    'text-align': 'left',
    color: '#262a30',
    font: '500 380% Montserrat, sans-serif',
    padding: '0px 4% 0px 4%',
    margin: '8% 0% 0% 0%',
    transition: '.5s',
  },
  introductionLight: {
    'text-align': 'left',
    color: 'white',
    font: '500 380% Montserrat, sans-serif',
    // font: '600 270% Montserrat, sans-serif',
    padding: '0px 4% 0px 4%',
    margin: '8% 0% 0% 0%',
    transition: '.5s',
  },
  story: {
    color: '#262a30',
    margin: '-3% 0% 1% 0%',
    font: '400 140% Hind, sans-serif',
    padding: '0px 5% 0px 5%',
    'text-align': 'left',
    transition: '.5s',
    'line-height': 1.3,
  },
  storyLight: {
    color: 'white',
    margin: '-5% 0% 1% 0%',
    font: '400 140% Hind, sans-serif',
    padding: '0px 5% 0px 5%',
    'text-align': 'left',
    transition: '.5s',
    'line-height': 1.3,
  },
  underline: {
    'border-bottom': '1px solid currentColor',
    color: '#262a30',
    'text-decoration': 'none',
    'line-height': '.6',
    display: 'inline-block',
    '&:hover': { 'border-bottom': '2px solid currentColor' },
  },
  underlineLight: {
    'border-bottom': '1px solid currentColor',
    color: 'white',
    'text-decoration': 'none',
    'line-height': '.9',
    display: 'inline-block',
    '&:hover': {
      // color: '#3f51b5',
      'border-bottom': '2px solid currentColor',
    },
  },
  projectsButton: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 0%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  projectsButtonRight: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 2%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  projectsButtonLight: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 0%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  sentMessage: {
    font: '600 90% Montserrat, sans-serif',
    // 'text-transform': 'capitalize',
    transition: '.4s',
    margin: '8% 0% 8% 0%',
  },
  sentMessageLight: {
    font: '600 90% Montserrat, sans-serif',
    // 'text-transform': 'capitalize',
    transition: '.4s',
    color: 'white',
    margin: '8% 0% 8% 0%',
  },
  // formContainer: { padding: '2% 40% 2% 40%', margin: '0% 30% 2% 30%' },
  formButtonContainer: {
    'text-align': 'right',
  },
  formButton: {
    padding: '2% 4% 2% 4%',
    margin: '1% 2% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },

  formButtonLight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 2% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  formButtonRight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 0% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  formButtonRightLight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 0% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  socialIconsContainer: {
    color: '#252525',
    margin: '3% 5% 5.5% 4%',
    padding: '0px auto 0% auto',
    display: 'flex',
    transition: '.5s',
    'text-align': 'left',
    '&:hover > div': {
      opacity: 0.5,
      transition: '.5s',
      position: 'relative',
    },
    '&:hover > div:hover': {
      opacity: 1,
      transition: '.5s',
      position: 'relative',
    },
  },
  socialIconsContainerLight: {
    color: 'white',
    // width: 'fit-content',
    // height: '30px',
    margin: '3% 5% 5.5% 4%',
    padding: '0px auto 0% auto',
    // bottom: 10,
    display: 'flex',
    transition: '.5s',
    'text-align': 'left',
    '&:hover > div': {
      opacity: 0.5,
      transition: '.5s',
      position: 'relative',
    },
    '&:hover > div:hover': {
      opacity: 1,
      transition: '.5s',
      position: 'relative',
    },
  },
  linkedinSocialIconContainer: { marginTop: '-4px' },
  githubSocialIcons: {
    'font-size': '35px',
    display: 'inline-block',
    margin: '0px 5px',
  },
  linkedinSocialIcons: {
    'font-size': '45px',
    display: 'inline-block',
  },
  mediumIcon: {
    width: '35px',
    display: 'inline-block',
    filter:
      'invert(0%) sepia(30%) saturate(60%) hue-rotate(100deg) brightness(100%) contrast(118%)',
  },
  darkModeIcon: {
    'font-size': '40px',
    display: 'inline-block',
    transform: 'rotate(45deg)',
  },
  logoPicture: {
    width: '15%',
    'border-radius': 5,
    margin: '0% 0% -4% 1%',
    // 'text-align': 'center',
    transition: '.5s',
    'box-shadow': '-1px 1px 36px -16px rgba(0,0,0,1)',
  },
  logoPictureLight: {
    width: '13%',
    'border-radius': 5,
    transition: '.5s',
    'box-shadow': ' -1px 1px 39px -17px rgba(255,255,255,1)',
  },
  projectsHeader: {
    color: '#262a30',
    padding: '0px 20px 0px 20px',
    font: '500 50px Montserrat, sans-serif',
    margin: '2% 0 1% 0',
    'text-align': 'center',
    transition: '.5s',
  },
  projectsHeaderLight: {
    color: 'white',
    padding: '0px 20px 0px 20px',
    font: '500 50px Montserrat, sans-serif',
    margin: '10% 0 0 0',
    transition: '.5s',
  },

  projectContainerOne: {
    margin: '70px 0px 20px 0px',
    padding: '10px 20px 0px 20px',
  },
  GridListRootTest: {
    // overflow: 'hidden',
  },
  gridListTest: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    // 'text-align': 'center',
    // width: 700,
    // width: '200%',
    // transform: 'translateZ(0)',
    // flexWrap: 'nowrap',
    // 'overflow-y': 'scroll !important',
    // height: '100%',
    // transition: '.5s',
    // '&::-webkit-scrollbar': {
    //   width: '.5em',
    //   marginBottom: '10px',
    // position: 'relative',
    // },
    // '&::-webkit-scrollbar-track': {
    //   // boxShadow: 'inset 0 0 6px #000',
    //   // border: '#252525 solid 1px',
    //   backgroundColor: '#eeeeee',
    //   // 'border-radius': '5px',
    // },
    // '&::-webkit-scrollbar-thumb': {
    //   backgroundColor: '#262b2f',
    //   // 'border-radius': '5px',
    // },
  },
  card: {
    // maxWidth: '90%',
    maxWidth: '92%',
    // maxWidth: '100%',
    // border: '#262a30 solid 2px',
    marginTop: '5%',
    marginBottom: '3%',
    'box-shadow': '-1px 1px 38px -29px rgba(0,0,0,1)',
    // backgroundColor: '#262a30',
    '&:hover': {
      transition: '.5s ease',
      backgroundColor: 'none',
    },
  },

  media: {
    // width: '100%',
    height: '23.5vw',
    // height: '25.5vw',
    // height: 340, //2 columns
    // height: 220, // 3
    // height: 165, //4
  },
  mediaMobile: { height: '43.5vw' },
  actionArea: {
    '&:hover $focusHighlight': {
      opacity: 0,
    },
  },
  focusHighlight: {},
  projectTitle: {
    padding: '0px 0px 0px 1%',
    font: '600 180% Montserrat, sans-serif',
    color: '#262a30',
    'text-align': 'left',
  },
  projectDescription: {
    padding: '0px 0px 0px 1%',
    marginBottom: '-2%',
    font: '400 120% Hind, sans-serif',
    'text-align': 'left',
    color: '#262a30',

    // transition: '.5s',
    // 'z-index': 9,
  },
  projectDemoIcon: {
    'font-size': '40px',
    color: '#262a30',
  },
  projectCodeIcon: {
    'font-size': '33px',
    color: '#262a30',
  },
  testTile: {
    'align-items': 'center',
    'justify-content': 'center',
    // margin: '70px 20px 0px 20px',
    // padding: '10px 10px 10px 10px',
    position: 'relative',
    // 'max-width': '300px',
    // 'min-width': '100%',
    '&:hover': {
      // 'box-shadow': '1px 5px 25px -10px rgba(0,0,0,0.3);',
    },
  },
  projectIntroButton: {
    padding: '1% 3% 1% 3%',
    margin: '3% 1% 4% 0%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  projectMessageButton: {
    padding: '1% 2% 1% 2%',
    margin: '3% 0% 4% 1%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  imageTextContainerTest: {
    background: 'transparent',
    color: '#252525',
    'border-radius': '5px',
    position: 'absolute',
    bottom: 12,
    border: '#252525 solid 2px',
    transition: '.5s ease',
    opacity: 1,
    // height: '88%',
    height: '100%',
    '&:hover': {
      'box-shadow': '-1px 1px 36px -16px rgba(0,0,0,1)',
      background: 'white',
      // opacity: 0,
    },
  },
  projectPictureTest: {
    width: '103%',
    // width: '120%',
    marginTop: '45%',
    'border-radius': '3px',
    transition: '.5s',
    '&:hover': {
      // opacity: 0,
      // 'box-shadow': '0px 0px 0px 0px rgba(0,0,0,0);',
    },
  },
  imageTextContainerIcon: {
    'font-size': '40px',
    marginTop: '3%',
    marginLeft: '8%',
  },
  imageTextContainerTitle: {
    font: '600 120% Montserrat, sans-serif',
    marginTop: '5.5%',
    marginLeft: '2%',
  },

  imageTextContainerDescription: {
    // marginLeft: '2%',
    font: '500 100% Hind, sans-serif',
    borderTop: '#dbdbdb solid 1px',
    padding: '10px 0px 0px 0px',
    margin: '1% 8% 0 9%',
  },
  imageText: {
    display: 'flex',
  },
  projectButtonContainerTest: {
    margin: '-2.5% 0% 5% 7.5%',
    width: '100%',
    // height: '200px',
    // backgroundColor: '#252525',
    // display: 'flex',
  },
  buttonTest: {
    // position: 'absolute',
    // position: 'relative',
    padding: '15% 7% 15% 7%',
    'border-radius': 5,
    margin: '-40% 1% 2% 1%',
    'text-transform': 'capitalize',
    // color: '#252525',
    // border: '#252525 solid 2px',
    // backgroundColor: 'white',
    color: 'transparent',
    border: 'transparent',
    backgroundColor: 'transparent',
    transition: '.5s',
    'box-shadow': '0px 0px 0px 0px',
    // display: 'flex',
    '&:hover': {
      transition: '.5s',
      'box-shadow': '0px 0px 0px 0px',
      color: 'white',
      backgroundColor: '#252525',
    },
  },
  buttonLeftTest: {
    position: 'absolute',
    // position: 'relative',
    padding: '15% 7% 15% 7%',
    'border-radius': 5,
    margin: '-40% 2% 2% 3%',
    'text-transform': 'capitalize',
    color: '#252525',
    border: '#252525 solid 2px',
    backgroundColor: 'white',
    transition: '.5s',
    'box-shadow': '0px 0px 0px 0px',
    // display: 'flex',
    '&:hover': {
      transition: '.5s',
      'box-shadow': '0px 0px 0px 0px',
      color: 'white',
      backgroundColor: '#252525',
    },
  },
  buttonRightTest: {
    position: 'absolute',
    // position: 'relative',
    padding: '15% 7% 15% 7%',
    'border-radius': 5,
    margin: '-40% 25% 2% 45%',
    'text-transform': 'capitalize',
    color: '#252525',
    border: '#252525 solid 2px',
    backgroundColor: 'white',
    transition: '.5s',
    'box-shadow': '0px 0px 0px 0px',
    // display: 'flex',
    '&:hover': {
      transition: '.5s',
      'box-shadow': '0px 0px 0px 0px',
      color: 'white',
      backgroundColor: '#252525',
    },
  },
  buttonText: {
    font: '600 120% Montserrat, sans-serif',
  },
  herokuIcon: {
    margin: '0% 1% -2% 1%',
    float: 'right',
  },
  projectContainerTwo: {
    margin: '-35px 0px 40px 0px',
    padding: '20px 20px 0px 20px',
  },
  projectContainerThree: {
    padding: '10px 20px 0px 20px',
  },

  projectPicture: {
    width: '100%',
    display: 'block',
    'border-radius': '3px',
    '&:hover': {
      'box-shadow': '0px 4px 6px 0px',
    },
    'box-shadow': '0px 4px 6px 0px',
    transition: '.5s',
  },

  // overlay {

  // }
  projectPictureLight: {
    width: '100%',
    'border-radius': '3px',
    'box-shadow': '0px 1px 6px 0px #fff',
    '&:hover': {
      'box-shadow': '0px 1px 6px 0px #fff',
    },
    transition: '.5s',
  },
  projectPictureMobile: {
    // border: '#dbdbdb solid 2px',
    padding: '2px',
    //
    'border-radius': '5px',
    filter: 'grayscale(100%)',
    // 'box-shadow': '1px 5px 28px -20px rgba(0,0,0,0.3);',
    width: '60%',
    '&:hover': {
      'box-shadow': '1px 5px 25px -10px rgba(0,0,0,0.3);',
      // border: '#fff solid 2px',
      // 'box-shadow': '1px 46px 27px -21px rgba(0,0,0,0.3);',
      width: '61%',
      filter: 'grayscale(0%)',
    },
    transition: '.5s',
    // position: 'absolute',
  },
  projectPictureLightMobile: {
    'border-radius': '3px',
    width: '50%',

    'box-shadow': '0px 1px 3px 0px #fff',
    '&:hover': {
      'box-shadow': '0px 1px 6px 0px #fff',
    },
    transition: '.5s',
  },
  hrefLink: {
    'text-decoration': 'none',
    color: '#262a30',
  },
  hrefLinkLight: {
    'text-decoration': 'none',
    color: 'white',
  },

  projectDescriptionMobile: {
    // padding: '0px 90px 0px 90px',
    padding: '0px 10px 0px 10px',
    marginTop: '10px',
    font: '400 14px Hind, sans-serif',
    'text-align': 'center',
    color: '#262a30',

    transition: '.5s',
    'z-index': 9,
  },
  projectDescriptionLightMobile: {
    padding: '0px 10px 0px 10px',
    marginTop: '10px',
    font: '400 14px Hind, sans-serif',
    'text-align': 'center',
    color: 'white',
    transition: '.5s',
  },
  projectTitleLight: {
    font: '600 22px Montserrat, sans-serif',
    margin: '30px 0px 0px 0px',
    padding: '10px 20px 10px 20px',
    color: 'white',
    transition: '.5s',
  },
  projectDescriptionLight: {
    padding: '0px 10px 0px 10px',
    marginTop: '10px',
    font: '400 16px Hind, sans-serif',
    'text-align': 'center',
    color: 'white',
    transition: '.5s',
  },

  button: {
    'text-align': 'center',
    position: 'absolute',
    padding: '7px 12px 7px 12px',
    top: '93%',
    left: '50%',
    'border-radius': 3,
    transform: 'translate(-50%, -50%)',
    margin: 'auto',
    color: 'white',
    font: '500 16px Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#262b2f',
    transition: '.5s',
    '&:hover': {
      transition: '.5s',
      // color: '#34a1fd',
      backgroundColor: '#34a1fd',
    },
  },
  buttonLight: {
    'text-align': 'center',
    position: 'absolute',
    padding: '7px 12px 7px 12px',
    top: '93%',
    left: '50%',
    'border-radius': 3,
    transform: 'translate(-50%, -50%)',
    margin: 'auto',
    color: '#262b2f',
    font: '500 16px Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.5s',
    '&:hover': {
      transition: '.5s',
      // color: '#34a1fd',
      backgroundColor: '#34a1fd',
    },
  },

  GridListRoot: {
    display: 'grid',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    overflow: 'hidden',
    alignItems: 'flex-end',
  },
  gridList: {
    // width: 700,
    width: '100%',
    transform: 'translateZ(0)',
    flexWrap: 'nowrap',
    // 'overflow-y': 'scroll !important',
    height: '100%',
    transition: '.5s',
    '&::-webkit-scrollbar': {
      width: '.5em',
      marginBottom: '10px',
      position: 'relative',
    },
    '&::-webkit-scrollbar-track': {
      // boxShadow: 'inset 0 0 6px #000',
      // border: '#252525 solid 1px',
      backgroundColor: '#eeeeee',
      // 'border-radius': '5px',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: '#262b2f',
      // 'border-radius': '5px',
    },
  },
  gridListLight: {
    width: '102%',
    // width:'600px',
    transform: 'translateZ(0)',
    flexWrap: 'nowrap',
    // 'overflow-y': 'scroll !important',
    height: '102%',
    transition: '.5s',
    '&::-webkit-scrollbar': {
      width: '.5em',
      marginBottom: '10px',
      position: 'relative',
    },
    '&::-webkit-scrollbar-track': {
      // boxShadow: 'inset 0 0 6px #000',
      // border: '#252525 solid 1px',
      backgroundColor: '#000',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: 'white',
    },
  },
  form: {
    marginTop: '30%',
    marginLeft: '10%',
    marginBottom: '30%',
    width: '80%',
    color: '#252525',
  },
  formContainer: {
    font: '400 15px Hind, sans-serif',
    'text-transform': 'capitalize',
    color: '#252525',
  },
  cover: { width: 158 },

  formLabels: { font: '500 100% Montserrat, sans-serif', color: '#252525' },
  formLabelsLight: {
    font: '500 100% Montserrat, sans-serif',
    color: 'white',
  },
  formTitleLight: {
    // padding: '0px 5% 0px 5%',
    margin: '0% 10% -2% 1%',
    font: '600 230% Montserrat, sans-serif',
    color: 'white',
  },
  formTitle: {
    // padding: '0px 5% 0px 5%',
    margin: '0% 10% -2% 1%',
    font: '600 230% Montserrat, sans-serif',
  },
  notchedOutline: {
    borderWidth: '2px',
    borderColor: '#252525 !important',
  },
  notchedOutlineLight: {
    borderWidth: '2px',
    borderColor: 'white !important',
  },
  inputLight: {
    color: 'white',
    font: '400 100% Montserrat, sans-serif',
    '&:focus': {
      backgroundColor: 'transparent',
    },
  },
  input: {
    color: '#252525',
    font: '400 100% Montserrat, sans-serif',
    '&:focus': {
      backgroundColor: 'transparent',
    },
  },
});
export default styles;
