const styles = (theme) => ({
  root: {
    flexGrow: 1,
  },
  darkModeRoot: {
    flexGrow: 1,
    backgroundColor: '#252525',
    // height: '100%',
    height: '100vh',
  },
  darkMode: {
    backgroundColor: '#252525',
    transition: '.5s',
    // height: '100vh',
  },
  darkModeMessage: {
    backgroundColor: '#262a30',
    transition: '.5s',
    height: '100vh',
  },

  lightMode: {
    backgroundColor: 'white',
    transition: '.5s',
  },

  //Intro

  logoPicture: {
    width: '20%',
    'border-radius': 5,
    margin: '0% 0% -1% 1%',
    transition: '.5s',
    'box-shadow': '-1px 1px 36px -16px rgba(0,0,0,1)',
  },
  logoPictureLight: {
    width: '20%',
    'border-radius': 5,
    margin: '0% 0% -1% 1%',
    transition: '.5s',
    'box-shadow': ' -1px 1px 39px -17px rgba(255,255,255,1)',
  },
  introduction: {
    'text-align': 'left',
    color: '#262a30',
    font: '500 380% Montserrat, sans-serif',
    padding: '0px 4% 0px 4%',
    margin: '3% 0% 0% 0%',
    transition: '.5s',
  },
  introductionLight: {
    'text-align': 'left',
    color: 'white',
    font: '500 380% Montserrat, sans-serif',
    padding: '0px 4% 0px 4%',
    margin: '3% 0% 0% 0%',
    transition: '.5s',
  },
  story: {
    color: '#262a30',
    margin: '-2% 0% 1% 0%',
    font: '400 140% Hind, sans-serif',
    padding: '0px 5% 0px 5%',
    'text-align': 'left',
    transition: '.5s',
    'line-height': 1.3,
  },
  storyLight: {
    color: 'white',
    margin: '-2% 0% 1% 0%',
    font: '400 140% Hind, sans-serif',
    padding: '0px 5% 0px 5%',
    'text-align': 'left',
    transition: '.5s',
    'line-height': 1.3,
  },
  underline: {
    'border-bottom': '1px solid currentColor',
    color: '#262a30',
    'text-decoration': 'none',
    'line-height': '.6',
    display: 'inline-block',
    '&:hover': { 'border-bottom': '2px solid currentColor' },
  },
  underlineLight: {
    'border-bottom': '1px solid currentColor',
    color: 'white',
    'text-decoration': 'none',
    'line-height': '.9',
    display: 'inline-block',
    '&:hover': {
      // color: '#3f51b5',
      'border-bottom': '2px solid currentColor',
    },
  },
  projectsButton: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 0%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  projectsButtonRight: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 2%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      // 'box-shadow': ' 0px 0px 0px 0px white',
      // 'box-shadow': '0px 1px 6px 0px #252525',
    },
  },
  projectsButtonLight: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 0%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },

  projectsButtonLightRight: {
    padding: '3% 4% 3% 4%',
    margin: '6% 0% 4% 2%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '600 90% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  sentMessage: {
    font: '600 90% Montserrat, sans-serif',

    transition: '.4s',
    margin: '8% 0% 8% 0%',
  },
  sentMessageLight: {
    font: '600 90% Montserrat, sans-serif',

    transition: '.4s',
    color: 'white',
    margin: '8% 0% 8% 0%',
  },

  formButtonContainer: {
    'text-align': 'right',
  },
  formButton: {
    padding: '2% 4% 2% 4%',
    margin: '1% 2% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },

  formButtonLight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 2% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },

  formButtonRight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 0% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  formButtonRightLight: {
    padding: '2% 4% 2% 4%',
    margin: '1% 0% 2% 0%',
    'border-radius': 3,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  formButtonExit: {
    padding: '1% 3% 1% 3%',
    margin: '1% 0% 0% -1%',
    'border-radius': 3,
    float: 'right',
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#fff',
      backgroundColor: '#252525',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  formButtonExitLight: {
    padding: '1% 3% 1% 3%',
    margin: '1% 0% 0% -1%',
    'border-radius': 3,
    float: 'right',
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#fff',
    border: 'white solid 2px',
    font: '700 100% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
      'box-shadow': ' 0px 0px 0px 0px white',
    },
  },
  socialIconsContainer: {
    color: '#252525',
    margin: '3% 5% 5.5% 4%',
    padding: '0px auto 0% auto',
    display: 'flex',
    transition: '.5s',
    'text-align': 'left',
    '&:hover > div': {
      opacity: 0.5,
      transition: '.5s',
      position: 'relative',
    },
    '&:hover > div:hover': {
      opacity: 1,
      transition: '.5s',
      position: 'relative',
    },
  },
  socialIconsContainerLight: {
    color: 'white',
    margin: '3% 5% 5.5% 4%',
    padding: '0px auto 0% auto',
    display: 'flex',
    transition: '.5s',
    'text-align': 'left',
    '&:hover > div': {
      opacity: 0.5,
      transition: '.5s',
      position: 'relative',
    },
    '&:hover > div:hover': {
      opacity: 1,
      transition: '.5s',
      position: 'relative',
    },
  },
  linkedinSocialIconContainer: { marginTop: '-4px' },
  githubSocialIcons: {
    'font-size': '35px',
    display: 'inline-block',
    margin: '0px 5px',
  },
  linkedinSocialIcons: {
    'font-size': '45px',
    display: 'inline-block',
  },
  mediumIcon: {
    width: '35px',
    display: 'inline-block',
    filter:
      'invert(0%) sepia(30%) saturate(60%) hue-rotate(100deg) brightness(100%) contrast(118%)',
  },
  darkModeIcon: {
    'font-size': '40px',
    display: 'inline-block',
    transform: 'rotate(45deg)',
  },

  // Projects

  projectsHeader: {
    color: '#262a30',
    font: '500 250% Montserrat, sans-serif',
    margin: '2% 0 0% 0',
    transition: '.5s',
  },
  projectsHeaderLight: {
    color: 'white',
    font: '500 250% Montserrat, sans-serif',
    margin: '2% 0 0% 0',
    transition: '.5s',
  },

  gridList: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    // transform: 'translateZ(0)',
    // flexWrap: 'nowrap',
    // 'overflow-y': 'scroll !important',
    // height: '100%',
    // transition: '.5s',
    // '&::-webkit-scrollbar': {
    //   width: '.5em',
    //   marginBottom: '10px',
    // position: 'relative',
    // },
    // '&::-webkit-scrollbar-track': {
    //   // boxShadow: 'inset 0 0 6px #000',
    //   // border: '#252525 solid 1px',
    //   backgroundColor: '#eeeeee',
    //   // 'border-radius': '5px',
    // },
    // '&::-webkit-scrollbar-thumb': {
    //   backgroundColor: '#262b2f',
    //   // 'border-radius': '5px',
    // },
  },
  gridListLight: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  card: {
    // maxWidth: '90%',
    maxWidth: '92%',
    // maxWidth: '100%',
    marginTop: '5%',
    marginBottom: '3%',
    'box-shadow': '-1px 1px 38px -29px rgba(0,0,0,1)',
    '&:hover': {
      transition: '.5s ease',
      backgroundColor: 'none',
    },
  },
  cardLight: {
    backgroundColor: '#252525',
    maxWidth: '92%',
    color: 'white',
    marginTop: '5%',
    marginBottom: '3%',
    // border: 'white solid 1px',
    'box-shadow': '-1px 1px 46px -28px rgba(255,255,255,1)',
    '&:hover': {
      transition: '.5s ease',
      backgroundColor: 'none',
    },
  },
  media: {
    // width: '100%',
    height: '23.5vw',
    // height: '25.5vw',
    // height: 340, //2 columns
    // height: 220, // 3
    // height: 165, //4
  },
  mediaMobile: { height: '48.5vw' },
  actionArea: {
    '&:hover $focusHighlight': {
      opacity: 0,
    },
  },
  focusHighlight: {},
  projectTitle: {
    padding: '0px 0px 0px 1%',
    font: '600 180% Montserrat, sans-serif',
    color: '#262a30',
    'text-align': 'left',
  },
  projectTitleLight: {
    padding: '0px 0px 0px 1%',
    font: '600 180% Montserrat, sans-serif',
    color: 'white',
    'text-align': 'left',
  },
  projectDescription: {
    padding: '0px 0px 0px 1%',
    marginBottom: '-6%',
    font: '400 130% Hind, sans-serif',
    'text-align': 'left',
    color: '#262a30',
    // transition: '.5s',
    // 'z-index': 9,
  },
  projectTech: {
    margin: '0% 0px 1% 1.2%',
    font: '500 130% Hind, sans-serif',
    color: '#262a30',
    'text-align': 'left',
  },
  projectTechLight: {
    margin: '0% 0px 1% 1.2%',
    font: '500 130% Hind, sans-serif',
    color: '#fff',
    'text-align': 'left',
  },
  projectDescriptionLight: {
    padding: '0px 0px 0px -1%',
    marginBottom: '-4%',
    font: '400 130% Hind, sans-serif',
    'text-align': 'left',
    color: 'white',
  },
  projectDemoIcon: {
    'font-size': '40px',
    color: '#262a30',
  },
  projectCodeIcon: {
    'font-size': '33px',
    color: '#262a30',
  },
  projectDemoIconLight: {
    'font-size': '40px',
    color: 'white',
  },
  projectCodeIconLight: {
    'font-size': '33px',
    color: 'white',
  },
  tile: {
    'align-items': 'center',
    'justify-content': 'center',
    position: 'relative',
  },
  projectButtonsContainer: {
    // display: 'flex',
    // float: 'right',
    // textAlign: 'center',
    // position: 'absolute',
    // // top: '50%',
    // right: 0,
    // marginTop: '5%',
    // width: '150px',
    padding: '0% 0% 7% 0%',
    // transform: 'translateY(-50%)',
  },
  projectHomeButton: {
    padding: '1% 0% 1% 0%',
    margin: '0.5% 2% 2% 0%',
    // margin: '2% 2% 0% 0%',
    width: '46%',
    // width: '94%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
    },
  },
  projectHomeButtonLight: {
    padding: '1% 0% 1% 0%',
    margin: '0.5% 2% 2% 0%',
    // margin: '2% 2% 0% 0%',
    width: '46%',
    // width: '94%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
    },
  },
  projectMessageButton: {
    padding: '1% 0% 1% 0%',
    // margin: '1% 0% 4% 4%',
    margin: '.5% 0% 2% 2%',
    // margin: '2% 0% 0% 0%',
    width: '46%',
    // width: '94%',
    'border-radius': 5,

    'box-shadow': ' 0px 0px 0px 0px white',
    color: '#252525',
    border: '#252525 solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: 'white',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: 'white',
      backgroundColor: '#252525',
    },
  },
  projectMessageButtonLight: {
    padding: '1% 0% 1% 0%',
    // margin: '1% 0% 4% 4%',
    margin: '.5% 0% 2% 2%',
    // margin: '2% 0% 0% 0%',
    width: '46%',
    // width: '94%',
    'border-radius': 5,
    'box-shadow': ' 0px 0px 0px 0px white',
    color: 'white',
    border: 'white solid 2px',
    font: '600 110% Montserrat, sans-serif',
    'text-transform': 'capitalize',
    backgroundColor: '#252525',
    transition: '.4s',
    '&:hover': {
      transition: '.4s',
      color: '#252525',
      backgroundColor: 'white',
    },
  },

  projectButtonContainerTest: {
    margin: '-2.5% 0% 5% 7.5%',
    width: '100%',
  },

  hrefLink: {
    'text-decoration': 'none',
    color: '#262a30',
  },
  hrefLinkLight: {
    'text-decoration': 'none',
    color: 'white',
  },

  // button: {
  // filter: 'grayscale(0%)',
  // },

  // GridListRoot: {
  //   display: 'grid',
  //   flexWrap: 'wrap',
  //   justifyContent: 'space-around',
  //   overflow: 'hidden',
  //   alignItems: 'flex-end',
  // },

  // Form Styling
  form: {
    marginTop: '30%',
    marginLeft: '10%',
    marginBottom: '30%',
    width: '80%',
    color: '#252525',
  },
  formContainer: {
    font: '400 15px Hind, sans-serif',
    'text-transform': 'capitalize',
    color: '#252525',
  },
  cover: { width: 158 },

  formLabels: { font: '500 100% Montserrat, sans-serif', color: '#252525' },
  formLabelsLight: {
    font: '500 100% Montserrat, sans-serif',
    color: 'white',
  },
  formTitleLight: {
    margin: '0% 10% -2% 1%',
    font: '600 230% Montserrat, sans-serif',
    color: 'white',
  },
  formTitle: {
    margin: '0% 10% -2% 1%',
    font: '600 230% Montserrat, sans-serif',
  },
  notchedOutline: {
    borderWidth: '2px',
    borderColor: '#252525 !important',
  },
  notchedOutlineLight: {
    borderWidth: '2px',
    borderColor: 'white !important',
  },
  inputLight: {
    color: 'white',
    font: '400 100% Montserrat, sans-serif',
    '&:focus': {
      backgroundColor: 'transparent',
    },
  },
  input: {
    color: '#252525',
    font: '400 100% Montserrat, sans-serif',
    '&:focus': {
      backgroundColor: 'transparent',
    },
  },
});
export default styles;
